# This is a basic workflow to help you get started with Actions

name: CI_DOCKER

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
        # -v ${{ github.workspace }}/my.cnf:/etc/mysql/my.cnf
    # --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake = FALSE
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    
    - name:  install frappe using docker compose
      run: |
           git clone https://github.com/frappe/frappe_docker.git
           cd frappe_docker
           cd .devcontainer
           docker-compose --project-name library up -d 
           docker exec library_frappe_1 pwd 
           docker exec library_frappe_1 bench init --skip-redis-config-generation --frappe-branch version-12 frappe-bench
        
    
        
