# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt install git python-dev redis-server
        sudo apt-get install software-properties-common
        sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
        sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://ftp.ubuntu-tw.org/mirror/mariadb/repo/10.3/ubuntu xenial main'
        sudo apt-get update
        sudo apt-get install mariadb-server-10.3
        
        sudo apt-get install libmysqlclient-dev
        sudo chmod 777 /etc/mysql/my.cnf
        sudo cat /etc/mysql/my.cnf
        sudo echo "[mysqld]" >> /etc/mysql/my.cnf
        sudo echo    "character-set-client-handshake = FALSE">> /etc/mysql/my.cnf
        sudo echo    "character-set-server = utf8mb4">> /etc/mysql/my.cnf
        sudo echo    "collation-server = utf8mb4_unicode_ci">> /etc/mysql/my.cnf
        sudo echo    "[mysql]">> /etc/mysql/my.cnf
        sudo echo    "default-character-set = utf8mb4" >> /etc/mysql/my.cnf
        
        sudo service mysql restart
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        sudo python install.py --production --user Administrator
        cd frappe-bench
        bench new-site example.com
        bench get-app https://github.com/yaacine/Frappe_Tuto.git
        bench --site example.com install-app library_management
  
        
        
